### ISSUE TITLE
O mapa ta funcionando, mas cadê os ônibus?

### ISSUE THREAD

**Issue by athoscouto** [naumazeredo/bus-follower#2]
Para pegar a posição atual dos onibus é só usar a URL:
`http://dadosabertos.rio.rj.gov.br/apiTransporte/apresentacao/rest/index.cfm/onibus/{numero_da_linha}`
Com isso a gente recebe um JSON bonitinho com várias informações discriminadas das linhas.

Para pegar informações sobre o itinerário, podemos usar a URL:
`http://dadosabertos.rio.rj.gov.br/apiTransporte/Apresentacao/csv/gtfs/onibus/percursos/gtfs_linha{numero_dalinha}-shapes.csv`
Esse segundo nos da um CSV.

Pelo o que eu vi, fica difícil de saber o sentido que o ônibus ta indo. Porque ele não fala o sentido do ônibus. Além disso, a gente não tem informação de quais pontos do trajeto da linha pertencem a qual sentido, então não tem como fazer um matching entre a posição do veículo e a rota, ou a variação de posição dele e a rota para determinarmos o sentido.

Podemos pensar em outras maneiras, talvez prospectar as ruas do itinerário no site. O que acham?

**Comment by naumazeredo** [comment]
Dá pra colocar custom marker e usar a orientação do ônibus pra mostrar o ônibus na posição e orientação corretas
